apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubechaos
  labels:
    app: kubechaos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubechaos
  template:
    metadata:
      labels:
        app: kubechaos
    spec:
      containers:
      - name: app
        image: local/kubechaos:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kubechaos-svc
spec:
  type: NodePort
  selector:
    app: kubechaos
  ports:
  - name: kubechaos-port
    protocol: TCP
    port: 3000
    targetPort: 3000
