site_name: RSECon25 Workshop: Deploying a Web Application with Kubernetes
nav:
  - Home: intro.md
repo_url: https://github.com/rosalindfranklininstitute/rsecon25-intro-to-kubernetes
edit_uri: tree/main/tutorial
theme:
  name: material

